---
deployment:
  tasks:
    - export DEPLOYPATH=/home/reactiveme/public_html/zackroy.com
      - /bin/cp -R about $DEPLOYPATH
      - /bin/cp -R app $DEPLOYPATH
      - /bin/cp -R book $DEPLOYPATH
      - /bin/cp -R contact $DEPLOYPATH
      - /bin/cp -R css $DEPLOYPATH
      - /bin/cp -R files $DEPLOYPATH
      - /bin/cp -R faq $DEPLOYPATH
      - /bin/cp -R images $DEPLOYPATH
      - /bin/cp -R js $DEPLOYPATH
      - /bin/cp -R plans $DEPLOYPATH
      - /bin/cp -R reviews $DEPLOYPATH
      - /bin/cp -R upload $DEPLOYPATH
      - /bin/cp index.php $DEPLOYPATH